ALTER TABLE `dsc_snatch_log`
MODIFY COLUMN `log_id`  int(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST ,
MODIFY COLUMN `snatch_id`  int(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `log_id`,
MODIFY COLUMN `user_id`  int(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `snatch_id`;
